site_name: AIGraph4pg
repo_url: https://github.com/cjoakim/AIGraph4pg
theme:
  name: material
  custom_dir: mkdocs_overrides
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

# nav: controls which docs/*.md files are included in the
# navigation UI, and their sequence.
# Default is all *.md files in an alphanumeric order.
nav:
  - index.md
  - Setup:
    - pg_local_installation.md
    - quick_start.md
    - pg_extensions.md
  - Tutorial:
    - tutorial_architecture.md
    - tutorial_pg_admin.md
    - tutorial_relational.md
    - tutorial_graph.md
    - tutorial_vector_search.md
    - tutorial_opencypher_gen.md
  - Reference:
    - psql_commands.md
  - faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# =============================================================================
#
# Links:
# - https://squidfunk.github.io/mkdocs-material/reference/
# - https://squidfunk.github.io/mkdocs-material/customization/
#   overrides/partials/footer.html as an example override of mkdocs-material
#
# Command-Line Usage:
#   mkdocs --help
#   mkdocs build --help
#   mkdocs build
#   mkdocs serve
#   mkdocs gh-deploy
